CC       = scpathcc
CFLAGS   = -gnu3 -g -O2 -Winline -DFORTRANDOUBLEUNDERSCORE  -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DLINUX=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_TIMES=1 -DFDEFS=1 -DHAVE_VPRINTF=1   

LIBNAME  = libgptl.a
LIBDIR   = /home/jrosinski/sim/lib
INCDIR   = /home/jrosinski/sim/include
MANDIR   = /home/jrosinski/man/man3
OBJS     = camwrappers.o f_wrappers.o gptl.o util.o threadutil.o get_memusage.o \
           print_memusage.o gptl_papi.o

# Use scar X32 for 32-bit
AR       = scar

$(LIBNAME): $(OBJS)
	$(AR) ruv $@ $(OBJS)
	rm -f ctests/*.o ftests/*.o

all: $(LIBNAME) ctests/all ftests/all

install: $(LIBNAME)
	cp $(LIBNAME) $(LIBDIR)
	cp gptl.h gptl.inc $(INCDIR)
	cp man/man3/*.3 $(MANDIR)

uninstall:
	rm -f $(LIBDIR)/$(LIBNAME) $(INCDIR)/gptl.h $(INCDIR)/gptl.inc

ctests/all:
	(cd ctests && $(MAKE) all -f Makefile.cross)

ftests/all:
	(cd ftests && $(MAKE) all -f Makefile.cross)

clean:
	rm -f $(OBJS) $(LIBNAME)
	(cd ctests && $(MAKE) clean)
	(cd ftests && $(MAKE) clean)

camwrappers.o: gptl.h private.h
f_wrappers.o: gptl.h private.h
gptl.o: gptl.h private.h
util.o: gptl.h private.h
threadutil.o: gptl.h private.h
gptl_papi.o: gptl.h private.h
