.\" $Id: GPTinitialize.3,v 1.2 2004-11-17 04:55:35 rosinski Exp $
.TH GPTinitialize 3 "November, 2004" "GPT"

.SH NAME
GPTinitialize \- Initialize GPT to allow subsequent calls to GPTstart and GPTstop.

.SH SYNOPSIS
.B C Interface:

.BI "int\ GPTinitialize (void);"

.fi
.B Fortran Interface:

.BI "integer gptinitialize ()"
.fi

.SH DESCRIPTION
.B GPTinitialize
Initializes the GPT library for subsequent calls to GPTstart and GPTstop.
This function MUST be called AFTER all calls to GPTsetoption and BEFORE all
calls to GPTstart and GPTstop.

.SH RETURN VALUES
On success, this function returns
.B 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

if (GPTinitialize () != 0)
  handle_error (1);

.if t .ft P
.fi

.SH SEE ALSO
.BR GPTsetoption "(3)" 
