.\" $Id: GPTLenable.3,v 1.2 2007-04-17 20:09:03 rosinski Exp $
.TH GPTLenable 3 "February, 2007" "GPTL"

.SH NAME
.nf
GPTLenable \- Enable timer start/stop calls
GPTLdisable \- Disable timer start/stop calls
.fi

.SH SYNOPSIS
.B C Interface:
.nf
int GPTLenable (void);
int GPTLdisable (void);
.fi

.B Fortran Interface:
.nf
integer gptlenable ()
integer gptldisable ()
.fi

.SH DESCRIPTION
.B GPTLenable():
Subsequent calls to
.B GPTLstart()
and
.B GPTLstop()
will be recognized. This is the initial state of the GPTL library.

.B GPTLdisable():
Subsequent calls to
.B GPTLstart()
and
.B GPTLstop()
will be ignored.

.SH RESTRICTIONS
None.

.SH RETURN VALUES
On success, these functions return 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

(void) GPTLenable ();
(void) GPTLstart ("timer1"); // this will be recognized
(void) GPTLstop ("timer1");  // this will be recognized
(void) GPTLdisable ();
(void) GPTLstart ("timer2"); // this will be ignored
(void) GPTLstop ("timer2");  // this will be ignored

.if t .ft P
.fi
