.\" $Id: GPTLpr_summary.3,v 1.4 2008-08-18 22:47:25 rosinski Exp $
.TH GPTLpr_summary 3 "April, 2007" "GPTL"

.SH NAME
GPTLpr_summary \- Print a counter summary across all threads and tasks

.SH SYNOPSIS
.B C Interface:
.nf
int GPTLpr_summary (int comm);
.fi

.B Fortran Interface:
.nf
integer gptlpr_summary (integer comm)
.fi

.SH DESCRIPTION
This routine is both experimental and deprecated. Suggest using
post-processing script
.B parsegptlout.pl
instead. GPTLpr_summary() summarizes stats across all threads and tasks to a file named 
.B timing.summary.
If MPI is enabled, this routine must be called before MPI_Finalize. Only
regions which exist for thread 0, task 0 are considered.

.SH ARGUMENTS
.I comm
-- MPI communicator to sum across. An input of 0 means use MPI_COMM_WORLD

.SH RESTRICTIONS
.B GPTLinitialize()
must have been called. To obtain any useful data, one or more
pairs of 
.B GPTLstart()/GPTLstop()
calls need to have been exercised.

.SH RETURN VALUES
On success, this function returns 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLE OUTPUT
None yet provided.

.SH BUGS
Only regions specified by task 0, thread 0 are checked. No indentation is
performed. Building GPTL with MPI enabled means all executables
linked with it will require MPI also be linked in, whether or not it's
needed. This could be fixed by building GPTL as a shared library.

.SH SEE ALSO
.BR GPTLpr "(3)" 
.BR GPTLpr_file "(3)" 
