.\" $Id: GPTLsetoption.3,v 1.1 2007-02-20 22:39:19 rosinski Exp $
.TH GPTLsetoption 3 "February, 2007" "GPTL"

.SH NAME
GPTLsetoption \- Enable or disable a GPTL (or PAPI if available) option.

.SH SYNOPSIS
.B C Interface:

.nf
.B #include <gptl.h>

.BI "int\ GPTLsetoption (const int option, const int val);"

.fi
.B Fortran Interface:

.nf
.B #include <gptl.inc>
.B #include <fpapi.h> (for PAPI options if PAPI support is enabled)

.BI "integer gptlsetoption (integer " option ", integer " val ")"
.fi

.SH DESCRIPTION
.B GPTLsetoption
enables or disables an option (e.g. gathering CPU stats, or enabling a PAPI
option such as PAPI_FP_OPS).  This function MUST be called BEFORE GPTLinitialize.

.SH ARGUMENTS
.I "option"
--  an integer specifying the option to be enabled or disabled.  Available
options are defined in gptl.h (gptl.inc for Fortran).  And in papi.h (fpapi.h
for Fortran) if PAPI support is enabled.
.BR
.LP
.I val
-- an integer defining whether to enable or disable
.BR option.
Non-zero values mean enable, and a zero value means to disable the option.

.SH RESTRICTIONS
Zero or more invocations of this function must be made prior to
GPTLinitialize. It cannot be called after GPTLinitialize.

.SH RETURN VALUES
On success, this function returns
.B 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

if (GPTLsetoption (GPTLcpu, 1) != 0)        /* Enable cpu timing */
  handle_error (1);
if (GPTLsetoption (PAPI_TOT_CYC, 1) != 0)   /* Enable counting total cycles */
  handle_error (1);

.if t .ft P
.fi

.SH SEE ALSO
.BR GPTLinitialize "(3)" 
