.\" $Id: GPTLenable.3,v 1.1 2007-02-20 22:39:18 rosinski Exp $
.TH GPTLenable 3 "February, 2007" "GPTL"

.SH NAME
GPTLenable \- Enable timer start/stop calls
GPTLdisable \- Disable timer start/stop calls

.SH SYNOPSIS
.B C Interface:

.BI "int\ GPTLenable (void);"
.BI "int\ GPTLdisable (void);"

.fi
.B Fortran Interface:

.BI "integer gptlenable ()"
.BI "integer gptldisable ()"
.fi

.SH DESCRIPTION
.B GPTLenable
Subsequent calls to GPTLstart and GPTLstop will be recognized.
.B name.

.B GPTLdisable
Subsequent calls to GPTLstart and GPTLstop will be ignored.
.B name.

.SH RESTRICTIONS
None.

.SH RETURN VALUES
On success, these functions return
.B 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

(void) GPTLenable ();
(void) GPTLstart ("timer1"); // this will be recognized
(void) GPTLstop ("timer1");  // this will be recognized
(void) GPTLdisable ();
(void) GPTLstart ("timer2"); // this will be ignored
(void) GPTLstop ("timer2");  // this will be ignored

.if t .ft P
.fi
