.TH GPTLreset_timer 3 "May, 2020" "GPTL"

.SH NAME
GPTLreset_timer \- Reset all timer contents to zero. 

.SH SYNOPSIS
.B C/C++ Interface:
.nf
#include <gptl.h>
int GPTLreset_timer (const char *name);
.fi

.B Fortran Interface:
.nf
use gptl
integer gptlreset_timer (character(len=*) name)
.fi

.SH DESCRIPTION
Reset timer "name" to zero.  This includes any embedded PAPI counters.

.SH RESTRICTIONS
.B GPTLinitialize()
must have been called. This function must be called by the master thread only.

.SH RETURN VALUES
On success, this function returns 0.
On error, a negative error code is returned and a descriptive message is printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

if (GPTLreset_timer ("some_timer") != 0)
  handle_error (1);

.if t .ft P
.fi
