.\" $Id: GPTreset.3,v 1.1 2004-11-17 04:55:35 rosinski Exp $
.TH GPTreset 3 "November, 2004" "GPT"

.SH NAME
GPTreset \- Reset all timers. IMPORTANT NOTE: this function has no effect on
PAPI counters.  Only metrics countable by GPT itself (currently cpu time and
wallclock time) can be reset.

.SH SYNOPSIS
.B C Interface:

.BI "int\ GPTreset (void);"

.fi
.B Fortran Interface:

.BI "integer gptreset ()"
.fi

.SH DESCRIPTION
.B GPTreset
Reset all timers (except PAPI counters) to zero.  This function must be
called by the master thread only.

.SH RETURN VALUES
On success, this function returns
.B 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

if (GPTreset () != 0)
  handle_error (1);

.if t .ft P
.fi
