.\" $Id: GPTsetoption.3,v 1.2 2004-11-17 04:55:35 rosinski Exp $
.TH GPTsetoption 3 "November, 2004" "GPT"

.SH NAME
GPTsetoption \- Enable or disable a GPT (or PAPI if available) option.

.SH SYNOPSIS
.B C Interface:

.nf

.BI "int\ GPTsetoption (void);"

.fi
.B Fortran Interface:

.nf
.B #include <gpt.inc>
.B #include <fpapi.h> (for PAPI options if PAPI support is enabled)

.BI "integer gptsetoption (integer " option ", integer " val ")"
.fi

.SH DESCRIPTION
.B GPTsetoption
enables or disables a counter (e.g. wallclock time).  This function MUST be
called BEFORE GPTinitialize if PAPI support is enabled.

.SH ARGUMENTS
.I "option"
--  an integer specifying an option to be enabled or disabled.  Available
options are defined in gpt.h (gpt.inc for Fortran).  And in papi.h (fpapi.h
for Fortran) if PAPI support is enabled.
.BR
.LP
.I val
-- an integer defining whether to enable or disable
.BR option.
Non-zero values mean enable, and a zero value means to disable the option.

.SH RETURN VALUES
On success, this function returns
.B 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

if (GPTsetoption (GPTcpu, 1) != 0)        /* Enable cpu timing */
  handle_error (1);
if (GPTsetoption (PAPI_TOT_CYC, 1) != 0)  /* Enable counting total cycles */
  handle_error (1);

.if t .ft P
.fi

.SH SEE ALSO
.BR GPTinitialize "(3)" 
