.\" $Id: GPTstamp.3,v 1.1 2004-11-17 04:55:35 rosinski Exp $
.TH GPTstamp 3 "November, 2004" "GPT"

.SH NAME
GPTstamp \- Return wallclock, user time, and system time stamps to the caller.

.SH SYNOPSIS
.B C Interface:

.BI "int\ GPTstamp (double *wall, double *usr, double *sys);"

.fi
.B Fortran Interface:

.BI "integer gptstamp (double precision wall, double precision usr, double precision sys)"
.fi

.SH DESCRIPTION
.B GPTstamp
Fill input arguments with wallclock, user time, and system time stamps.

.SH RETURN VALUES
On success, this function returns
.B 0.
On error, a negative error code is returned and a descriptive message
printed. 

.SH EXAMPLES
.nf         
.if t .ft CW

if (GPTstamp (wall, usr, sys) != 0)
  handle_error (1);

.if t .ft P
.fi
